/**
 * FILE: data.js
 * Contains the tech tree structure provided by the user.
 */
export const initialData = {
    nodes: [
      {
        id: "armed-patrols",
        type: "custom",
        data: {
          label: "Armed Patrols",
          cost: 500,
          building: "City Watch",
          income: "—",
          rewards: "Once per arc, gain advantage on an initiative or chase roll",
        },
        position: { x: 0, y: 0 },
      },
      {
        id: "watch-barracks",
        type: "custom",
        data: {
          label: "Watch Barracks",
          cost: 1000,
          building: "City Watch",
          income: "—",
          rewards: "Once per arc, ignore surprise in one combat",
        },
        position: { x: 300, y: 0 },
      },
      {
        id: "elite-guard-program",
        type: "custom",
        data: {
          label: "Elite Guard Program",
          cost: 1500,
          building: "City Watch",
          income: "—",
          rewards: "Once per arc, declare allied scouts were active in the area",
        },
        position: { x: 600, y: 0 },
      },
      {
        id: "civic-wardens",
        type: "custom",
        data: {
          label: "Civic Wardens",
          cost: 2500,
          building: "City Watch",
          income: "—",
          rewards:
            "Once per arc: mid-scene reinforcements, secure extraction, or battlefield preparation",
        },
        position: { x: 900, y: 0 },
      },
  
      {
        id: "expanded-warehouses",
        type: "custom",
        data: {
          label: "Expanded Warehouses",
          cost: 500,
          building: "The River Store",
          income: "+10%",
          rewards: "Freely acquire mundane expedition gear",
        },
        position: { x: 0, y: 200 },
      },
      {
        id: "trade-contracts",
        type: "custom",
        data: {
          label: "Trade Contracts",
          cost: 1000,
          building: "The River Store",
          income: "+5%",
          rewards: "Uncommon adventuring gear always available",
        },
        position: { x: 300, y: 200 },
      },
      {
        id: "merchant-guild",
        type: "custom",
        data: {
          label: "Merchant Guild",
          cost: 1500,
          building: "The River Store",
          income: "+15%",
          rewards: "Once per arc, refresh consumables mid-adventure",
        },
        position: { x: 600, y: 200 },
      },
      {
        id: "trade-fleet",
        type: "custom",
        data: {
          label: "Trade Fleet",
          cost: 2500,
          building: "The River Store",
          income: "+10%",
          rewards: "Once per arc, rapid delivery or retrieval of an item",
        },
        position: { x: 900, y: 200 },
      },
  
      {
        id: "bounty-board",
        type: "custom",
        data: {
          label: "Bounty Board",
          cost: 250,
          building: "The Huntress",
          income: "+2%",
          rewards: "Gain one bounty hook with guaranteed payoff",
        },
        position: { x: 0, y: 400 },
      },
      {
        id: "hunter-circles",
        type: "custom",
        data: {
          label: "Hunter Circles",
          cost: 750,
          building: "The Huntress",
          income: "+3%",
          rewards: "Monster components replace missing crafting materials",
        },
        position: { x: 300, y: 400 },
      },
      {
        id: "master-hunts",
        type: "custom",
        data: {
          label: "Master Hunts",
          cost: 1250,
          building: "The Huntress",
          income: "+5%",
          rewards: "Once per arc, gain a powerful situational consumable",
        },
        position: { x: 600, y: 400 },
      },
      {
        id: "trophy-hall",
        type: "custom",
        data: {
          label: "Trophy Hall",
          cost: 2000,
          building: "The Huntress",
          income: "+5%",
          rewards: "Begin one hunt with full intel on the target",
        },
        position: { x: 900, y: 400 },
      },
  
      {
        id: "apothecary-expansion",
        type: "custom",
        data: {
          label: "Apothecary Expansion",
          cost: 500,
          building: "House of Healing",
          income: "+5%",
          rewards: "Gain 2 healing potions per arc",
        },
        position: { x: 0, y: 600 },
      },
      {
        id: "specialized-elixirs",
        type: "custom",
        data: {
          label: "Specialized Elixirs",
          cost: 1000,
          building: "House of Healing",
          income: "+5%",
          rewards: "Resistance, antitoxin, and restoration elixirs available",
        },
        position: { x: 300, y: 600 },
      },
      {
        id: "advanced-remedies",
        type: "custom",
        data: {
          label: "Advanced Remedies",
          cost: 1500,
          building: "House of Healing",
          income: "+5%",
          rewards: "Commission one custom potion per arc",
        },
        position: { x: 600, y: 600 },
      },
      {
        id: "alchemical-mastery",
        type: "custom",
        data: {
          label: "Alchemical Mastery",
          cost: 2500,
          building: "House of Healing",
          income: "—",
          rewards: "Once per arc, negate a debilitating condition on the party",
        },
        position: { x: 900, y: 600 },
      },
  
      {
        id: "reinforced-forges",
        type: "custom",
        data: {
          label: "Reinforced Forges",
          cost: 500,
          building: "The Bronze Hoof",
          income: "+5%",
          rewards: "Upgrade mundane gear to masterwork",
        },
        position: { x: 0, y: 800 },
      },
      {
        id: "masterwork-arms",
        type: "custom",
        data: {
          label: "Masterwork Arms",
          cost: 1000,
          building: "The Bronze Hoof",
          income: "+5%",
          rewards: "Reduce crafting downtime",
        },
        position: { x: 300, y: 800 },
      },
      {
        id: "enchanted-fittings",
        type: "custom",
        data: {
          label: "Enchanted Fittings",
          cost: 1500,
          building: "The Bronze Hoof",
          income: "—",
          rewards: "Safely apply or swap enchantments",
        },
        position: { x: 600, y: 800 },
      },
      {
        id: "relic-reinforcement",
        type: "custom",
        data: {
          label: "Relic Reinforcement",
          cost: 2500,
          building: "The Bronze Hoof",
          income: "—",
          rewards: "Once per arc, permanently enhance a magic item",
        },
        position: { x: 900, y: 800 },
      },
  
      {
        id: "deepwood-patrols",
        type: "custom",
        data: {
          label: "Deepwood Patrols",
          cost: 500,
          building: "Warden’s Den",
          income: "—",
          rewards: "Once per arc, ignore natural terrain penalties",
        },
        position: { x: 0, y: 1000 },
      },
      {
        id: "border-wards",
        type: "custom",
        data: {
          label: "Border Wards",
          cost: 1000,
          building: "Warden’s Den",
          income: "—",
          rewards: "Auto-succeed one tracking or navigation check",
        },
        position: { x: 300, y: 1000 },
      },
      {
        id: "sacred-groves",
        type: "custom",
        data: {
          label: "Sacred Groves",
          cost: 1500,
          building: "Warden’s Den",
          income: "+5%",
          rewards: "Gain rare natural reagents usable as spell components",
        },
        position: { x: 600, y: 1000 },
      },
      {
        id: "primal-guardians",
        type: "custom",
        data: {
          label: "Primal Guardians",
          cost: 2500,
          building: "Warden’s Den",
          income: "—",
          rewards:
            "Once per arc, summon a primal entity to reshape a battlefield",
        },
        position: { x: 900, y: 1000 },
      },
  
      {
        id: "tax-reform",
        type: "custom",
        data: {
          label: "Tax Reform",
          cost: 500,
          building: "Council of Commerce",
          income: "+10%",
          rewards: "Convert gold to expedition resources at a discount",
        },
        position: { x: 0, y: 1200 },
      },
      {
        id: "investment-charters",
        type: "custom",
        data: {
          label: "Investment Charters",
          cost: 1000,
          building: "Council of Commerce",
          income: "+5%",
          rewards: "Once per arc, fund a preparation retroactively",
        },
        position: { x: 300, y: 1200 },
      },
      {
        id: "trade-monopolies",
        type: "custom",
        data: {
          label: "Trade Monopolies",
          cost: 1500,
          building: "Council of Commerce",
          income: "+10%",
          rewards: "Force access to restricted goods or services",
        },
        position: { x: 600, y: 1200 },
      },
      {
        id: "economic-leverage",
        type: "custom",
        data: {
          label: "Economic Leverage",
          cost: 2500,
          building: "Council of Commerce",
          income: "+5%",
          rewards: "Once per arc, compel cooperation from a neutral faction",
        },
        position: { x: 900, y: 1200 },
      },
  
      {
        id: "festival-program",
        type: "custom",
        data: {
          label: "Festival Program",
          cost: 250,
          building: "Council of Culture",
          income: "+5%",
          rewards: "Gain advantage on social checks for one adventure",
        },
        position: { x: 0, y: 1400 },
      },
      {
        id: "relic-exhibition",
        type: "custom",
        data: {
          label: "Relic Exhibition",
          cost: 750,
          building: "Council of Culture",
          income: "+5%",
          rewards: "Identify relics safely and instantly",
        },
        position: { x: 300, y: 1400 },
      },
      {
        id: "cultural-prestige",
        type: "custom",
        data: {
          label: "Cultural Prestige",
          cost: 1250,
          building: "Council of Culture",
          income: "+5%",
          rewards: "Once per arc, rewrite a faction’s perception of the Council",
        },
        position: { x: 600, y: 1400 },
      },
      {
        id: "myth-archive",
        type: "custom",
        data: {
          label: "Myth Archive",
          cost: 2000,
          building: "Council of Culture",
          income: "—",
          rewards: "Once per arc, suppress or amplify a rumor globally",
        },
        position: { x: 900, y: 1400 },
      },
  
      {
        id: "research-grants",
        type: "custom",
        data: {
          label: "Research Grants",
          cost: 500,
          building: "Council of Education",
          income: "—",
          rewards: "Ask one research question per week",
        },
        position: { x: 0, y: 1600 },
      },
      {
        id: "scholarly-orders",
        type: "custom",
        data: {
          label: "Scholarly Orders",
          cost: 1000,
          building: "Council of Education",
          income: "—",
          rewards: "Reduce downtime for study or crafting",
        },
        position: { x: 300, y: 1600 },
      },
      {
        id: "arcane-curriculum",
        type: "custom",
        data: {
          label: "Arcane Curriculum",
          cost: 1500,
          building: "Council of Education",
          income: "—",
          rewards: "Enables Nexus and enchantment systems",
        },
        position: { x: 600, y: 1600 },
      },
  
      {
        id: "formal-embassy",
        type: "custom",
        data: {
          label: "Formal Embassy",
          cost: 500,
          building: "Setessan Embassy",
          income: "+5%",
          rewards: "Advantage on diplomacy with allied factions",
        },
        position: { x: 0, y: 1800 },
      },
      {
        id: "diplomatic-staff",
        type: "custom",
        data: {
          label: "Diplomatic Staff",
          cost: 750,
          building: "Setessan Embassy",
          income: "+5%",
          rewards: "Once per arc, gain decisive political intel",
        },
        position: { x: 300, y: 1800 },
      },
      {
        id: "treaty-chambers",
        type: "custom",
        data: {
          label: "Treaty Chambers",
          cost: 1250,
          building: "Setessan Embassy",
          income: "+5%",
          rewards: "Force a parley instead of combat",
        },
        position: { x: 600, y: 1800 },
      },
      {
        id: "regional-accords",
        type: "custom",
        data: {
          label: "Regional Accords",
          cost: 2000,
          building: "Setessan Embassy",
          income: "+10%",
          rewards: "Once per arc, secure safe passage or a ceasefire",
        },
        position: { x: 900, y: 1800 },
      },
  
      {
        id: "permanent-camp",
        type: "custom",
        data: {
          label: "Permanent Camp",
          cost: 500,
          building: "Lagonna Lodge Camp",
          income: "+10%",
          rewards: "Retroactively declare correct expedition gear",
        },
        position: { x: 0, y: 2000 },
      },
      {
        id: "survey-teams",
        type: "custom",
        data: {
          label: "Survey Teams",
          cost: 750,
          building: "Lagonna Lodge Camp",
          income: "+5%",
          rewards: "Reveal one dungeon feature in advance",
        },
        position: { x: 300, y: 2000 },
      },
      {
        id: "deep-expeditions",
        type: "custom",
        data: {
          label: "Deep Expeditions",
          cost: 1250,
          building: "Lagonna Lodge Camp",
          income: "+10%",
          rewards: "Gain one rare crafting material per arc",
        },
        position: { x: 600, y: 2000 },
      },
      {
        id: "relic-logistics",
        type: "custom",
        data: {
          label: "Relic Logistics",
          cost: 2000,
          building: "Lagonna Lodge Camp",
          income: "+15%",
          rewards: "Obtain one pre-divine component per arc",
        },
        position: { x: 900, y: 2000 },
      },
  
      {
        id: "river-docks",
        type: "custom",
        data: {
          label: "River Docks",
          cost: 2000,
          building: "Port",
          income: "+40%",
          rewards: "Enables sea travel and naval logistics",
        },
        position: { x: 0, y: 2200 },
      },
      {
        id: "port-authority",
        type: "custom",
        data: {
          label: "Port Authority",
          cost: 750,
          building: "Port",
          income: "+5%",
          rewards: "Once per arc, expedite or intercept a shipment",
        },
        position: { x: 300, y: 2200 },
      },
      {
        id: "shipyards",
        type: "custom",
        data: {
          label: "Shipyards",
          cost: 1250,
          building: "Port",
          income: "+5%",
          rewards: "Upgrade a vessel or secure naval support",
        },
        position: { x: 600, y: 2200 },
      },
      {
        id: "trade-fleets",
        type: "custom",
        data: {
          label: "Trade Fleets",
          cost: 2000,
          building: "Port",
          income: "+10%",
          rewards: "Once per arc, rapid transit or evacuation",
        },
        position: { x: 900, y: 2200 },
      },
  
      {
        id: "aetherium-foundations",
        type: "custom",
        data: {
          label: "Aetherium Foundations",
          cost: 750,
          building: "Aetherium Nexus",
          income: "—",
          rewards: "Enables all magic-powered upgrades",
        },
        position: { x: 0, y: 2400 },
      },
      {
        id: "conduit-arrays",
        type: "custom",
        data: {
          label: "Conduit Arrays",
          cost: 1250,
          building: "Aetherium Nexus",
          income: "—",
          rewards: "Convert magic items into Nexus Charges",
        },
        position: { x: 300, y: 2400 },
      },
      {
        id: "power-regulation",
        type: "custom",
        data: {
          label: "Power Regulation",
          cost: 1750,
          building: "Aetherium Nexus",
          income: "—",
          rewards: "Once per arc, overcharge a spell or item",
        },
        position: { x: 600, y: 2400 },
      },
      {
        id: "arcane-distribution",
        type: "custom",
        data: {
          label: "Arcane Distribution",
          cost: 2000,
          building: "Aetherium Nexus",
          income: "—",
          rewards: "Nexus-based abilities usable anywhere",
        },
        position: { x: 900, y: 2400 },
      },
      {
        id: "teleportation-gate",
        type: "custom",
        data: {
          label: "Teleportation Gate",
          cost: 2500,
          building: "Aetherium Nexus",
          income: "—",
          rewards: "Once per arc, summon reinforcements or extract the party",
        },
        position: { x: 1200, y: 2400 },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "armed-patrols",
        target: "watch-barracks",
        animated: true,
      },
      {
        id: "e2",
        source: "watch-barracks",
        target: "elite-guard-program",
        animated: true,
      },
      {
        id: "e3",
        source: "elite-guard-program",
        target: "civic-wardens",
        animated: true,
      },
      {
        id: "e4",
        source: "arcane-distribution",
        target: "civic-wardens",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e5",
        source: "expanded-warehouses",
        target: "trade-contracts",
        animated: true,
      },
      {
        id: "e6",
        source: "trade-contracts",
        target: "merchant-guild",
        animated: true,
      },
      {
        id: "e7",
        source: "merchant-guild",
        target: "trade-fleet",
        animated: true,
      },
      {
        id: "e8",
        source: "investment-charters",
        target: "trade-contracts",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e9",
        source: "shipyards",
        target: "trade-fleet",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e10",
        source: "arcane-distribution",
        target: "trade-fleet",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e11",
        source: "bounty-board",
        target: "hunter-circles",
        animated: true,
      },
      {
        id: "e12",
        source: "hunter-circles",
        target: "master-hunts",
        animated: true,
      },
      {
        id: "e13",
        source: "master-hunts",
        target: "trophy-hall",
        animated: true,
      },
      {
        id: "e14",
        source: "festival-program",
        target: "master-hunts",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e15",
        source: "apothecary-expansion",
        target: "specialized-elixirs",
        animated: true,
      },
      {
        id: "e16",
        source: "specialized-elixirs",
        target: "advanced-remedies",
        animated: true,
      },
      {
        id: "e17",
        source: "advanced-remedies",
        target: "alchemical-mastery",
        animated: true,
      },
      {
        id: "e18",
        source: "research-grants",
        target: "advanced-remedies",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e19",
        source: "power-regulation",
        target: "alchemical-mastery",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e20",
        source: "reinforced-forges",
        target: "masterwork-arms",
        animated: true,
      },
      {
        id: "e21",
        source: "masterwork-arms",
        target: "enchanted-fittings",
        animated: true,
      },
      {
        id: "e22",
        source: "enchanted-fittings",
        target: "relic-reinforcement",
        animated: true,
      },
      {
        id: "e23",
        source: "arcane-curriculum",
        target: "enchanted-fittings",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e24",
        source: "arcane-distribution",
        target: "relic-reinforcement",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e25",
        source: "deepwood-patrols",
        target: "border-wards",
        animated: true,
      },
      {
        id: "e26",
        source: "border-wards",
        target: "sacred-groves",
        animated: true,
      },
      {
        id: "e27",
        source: "sacred-groves",
        target: "primal-guardians",
        animated: true,
      },
      {
        id: "e28",
        source: "research-grants",
        target: "border-wards",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e29",
        source: "specialized-elixirs",
        target: "sacred-groves",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e30",
        source: "arcane-distribution",
        target: "primal-guardians",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e31",
        source: "tax-reform",
        target: "investment-charters",
        animated: true,
      },
      {
        id: "e32",
        source: "investment-charters",
        target: "trade-monopolies",
        animated: true,
      },
      {
        id: "e33",
        source: "trade-monopolies",
        target: "economic-leverage",
        animated: true,
      },
      {
        id: "e34",
        source: "trade-contracts",
        target: "trade-monopolies",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e35",
        source: "port-authority",
        target: "economic-leverage",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e36",
        source: "festival-program",
        target: "relic-exhibition",
        animated: true,
      },
      {
        id: "e37",
        source: "relic-exhibition",
        target: "cultural-prestige",
        animated: true,
      },
      {
        id: "e38",
        source: "cultural-prestige",
        target: "myth-archive",
        animated: true,
      },
      {
        id: "e39",
        source: "diplomatic-staff",
        target: "cultural-prestige",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e40",
        source: "conduit-arrays",
        target: "myth-archive",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e41",
        source: "research-grants",
        target: "scholarly-orders",
        animated: true,
      },
      {
        id: "e42",
        source: "scholarly-orders",
        target: "arcane-curriculum",
        animated: true,
      },
  
      {
        id: "e43",
        source: "formal-embassy",
        target: "diplomatic-staff",
        animated: true,
      },
      {
        id: "e44",
        source: "diplomatic-staff",
        target: "treaty-chambers",
        animated: true,
      },
      {
        id: "e45",
        source: "treaty-chambers",
        target: "regional-accords",
        animated: true,
      },
      {
        id: "e46",
        source: "festival-program",
        target: "diplomatic-staff",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e47",
        source: "investment-charters",
        target: "treaty-chambers",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e48",
        source: "river-docks",
        target: "regional-accords",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e49",
        source: "conduit-arrays",
        target: "regional-accords",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e50",
        source: "permanent-camp",
        target: "survey-teams",
        animated: true,
      },
      {
        id: "e51",
        source: "survey-teams",
        target: "deep-expeditions",
        animated: true,
      },
      {
        id: "e52",
        source: "deep-expeditions",
        target: "relic-logistics",
        animated: true,
      },
      {
        id: "e53",
        source: "research-grants",
        target: "survey-teams",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e54",
        source: "deepwood-patrols",
        target: "deep-expeditions",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e55",
        source: "relic-exhibition",
        target: "relic-logistics",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e56",
        source: "conduit-arrays",
        target: "relic-logistics",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
      {
        id: "e57",
        source: "river-docks",
        target: "port-authority",
        animated: true,
      },
      {
        id: "e58",
        source: "port-authority",
        target: "shipyards",
        animated: true,
      },
      { id: "e59", source: "shipyards", target: "trade-fleets", animated: true },
      {
        id: "e60",
        source: "tax-reform",
        target: "port-authority",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e61",
        source: "reinforced-forges",
        target: "shipyards",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e62",
        source: "merchant-guild",
        target: "trade-fleets",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e63",
        source: "arcane-distribution",
        target: "trade-fleets",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
  
    {
      id: "e64",
      source: "arcane-curriculum",
      target: "aetherium-foundations",
      animated: true,
    },
      {
        id: "e65",
        source: "aetherium-foundations",
        target: "conduit-arrays",
        animated: true,
      },
      {
        id: "e66",
        source: "conduit-arrays",
        target: "power-regulation",
        animated: true,
      },
      {
        id: "e67",
        source: "power-regulation",
        target: "arcane-distribution",
        animated: true,
      },
      {
        id: "e68",
        source: "arcane-distribution",
        target: "teleportation-gate",
        animated: true,
      },
      {
        id: "e69",
        source: "advanced-remedies",
        target: "power-regulation",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e70",
        source: "enchanted-fittings",
        target: "arcane-distribution",
        data: { isCrossChain: true },
        style: { strokeDasharray: "5,5" },
      },
    ],
  };
  